source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

pod 'pop'

target 'Pop Demo 1' do

end

target 'Pop Demo 1Tests' do

end

